/**
* This is Product_Page where there are three buttons available Add_Products, View_Products, and Delete_Products
* 
*/

import java.sql.*;
import javax.swing.*;


/*
* Date created :31-March-2019
*
* @author Jayesh Varchand
*/

public class ProductPage extends javax.swing.JFrame {

/**     
* Creates new page ProductPage     
*/

    public ProductPage() {

        initComponents();

    }


    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          

    private void initComponents() {


        jPanel1 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();

        jButton1 = new javax.swing.JButton();

        jButton2 = new javax.swing.JButton();

        jButton3 = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        jPanel1.setBackground(new java.awt.Color(0, 255, 255));


        jLabel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));  // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setText(" PRODUCTS");


        jButton1.setText("ADD");


        jButton2.setText("VIEW");


        jButton3.setText("DELETE");


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);

        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
	.addGap(72, 72, 72)
	.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	.addComponent(jButton2,javax.swing.GroupLayout.PREFERRED_SIZE,69,javax.swing.GroupLayout.PREFERRED_SIZE)
	.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
	.addComponent(jLabel1,javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
	.addComponent(jButton3))
	.addContainerGap(205, Short.MAX_VALUE))
         );

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	/*	try
		{
			
                        if(r1.next())
                            {
				AddProductPage h1=new AddProductPage();
				h1.setVisible(true);
				h1.pack();
				h1.setLocationRelativeTo(null);
				h1.setExtendedState(JFrame.MAXIMIZED_BOTH);
				this.dispose();
				}
                        else
                            System.out.println("NO");
		}
	
		catch (Exception e)
		{
			System.out.println("  " +e.getMessage());
		}
	*/
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	/*
        try
		{
			
                        if(r1.next())
                            {
				ViewProductPage h1=new ViewProductPage();
				h1.setVisible(true);
				h1.pack();
				h1.setLocationRelativeTo(null);
				h1.setExtendedState(JFrame.MAXIMIZED_BOTH);
				this.dispose();
				}
                        else
                            System.out.println("NO");
		}
	
		catch (Exception e)
		{
			System.out.println("  " +e.getMessage());
		}
	*/
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	/*	try
		{
			
                        if(r1.next())
                            {
				DeleteProductPage h1=new DeleteProductPage();
				h1.setVisible(true);
				h1.pack();
				h1.setLocationRelativeTo(null);
				h1.setExtendedState(JFrame.MAXIMIZED_BOTH);
				this.dispose();
				}
                        else
                            System.out.println("NO");
		}
	
		catch (Exception e)
		{
			System.out.println("  " +e.getMessage());
		}
	*/
    }
                          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
